-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.album_t;--Xiaohang Ji 12-11
(
    album_id integer NOT NULL,
    album_name character varying(20) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT pk_album_id PRIMARY KEY (album_id)
)
WITH (
    OIDS = FALSE
);

CREATE TABLE IF NOT EXISTS public.label_t;--Xiaohang Ji 12-11
(
    label_id integer NOT NULL,
    label_name character varying(20) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "pk_ label_id" PRIMARY KEY (label_id)
)
WITH (
    OIDS = FALSE
);

CREATE TABLE IF NOT EXISTS public.listener_t;--Xiaohang Ji 12-11
(
    listener_name character varying(20) COLLATE pg_catalog."default" NOT NULL,
    email character varying(20) COLLATE pg_catalog."default" NOT NULL,
    music_id integer NOT NULL,
    CONSTRAINT "fk_ listener_name" PRIMARY KEY (listener_name)
)
WITH (
    OIDS = FALSE
);

CREATE TABLE IF NOT EXISTS public.music_listener_int;--Xiaohang Ji 12-11
(
    listener_name character varying(20) COLLATE pg_catalog."default",
    music_id integer
)
WITH (
    OIDS = FALSE
);

CREATE TABLE IF NOT EXISTS public.music_t;--Xiaohang Ji 12-11
(
    music_id integer NOT NULL,
    music_name character varying(20) COLLATE pg_catalog."default" NOT NULL,
    singer_id integer NOT NULL,
    label_id integer NOT NULL,
    album_id integer NOT NULL,
    CONSTRAINT " pk_music_id" PRIMARY KEY (music_id)
)
WITH (
    OIDS = FALSE
);

CREATE TABLE IF NOT EXISTS public.singer_t;--Xiaohang Ji 12-11
(
    singer_id integer NOT NULL,
    singer_name character varying(20) COLLATE pg_catalog."default" NOT NULL,
    gender character varying(20) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT pk_singer_id PRIMARY KEY (singer_id)
)
WITH (
    OIDS = FALSE
);

ALTER TABLE IF EXISTS public.music_listener_int;--Xiaohang Ji 12-11
    ADD CONSTRAINT music_listener_int_listener_name_fkey FOREIGN KEY (listener_name)
    REFERENCES public.listener_t (listener_name) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.music_listener_int;--Xiaohang Ji 12-11
    ADD CONSTRAINT music_listener_int_music_id_fkey FOREIGN KEY (music_id)
    REFERENCES public.music_t (music_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.music_t;--Xiaohang Ji 12-11
    ADD CONSTRAINT music_t_album_id_fkey FOREIGN KEY (album_id)
    REFERENCES public.album_t (album_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.music_t;--Xiaohang Ji 12-11
    ADD CONSTRAINT music_t_label_id_fkey FOREIGN KEY (label_id)
    REFERENCES public.label_t (label_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.music_t;--Xiaohang Ji 12-11
    ADD CONSTRAINT music_t_singer_id_fkey FOREIGN KEY (singer_id)
    REFERENCES public.singer_t (singer_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;